### ISSUE TITLE
Compilation fails: Error compiling Cython file

### ISSUE THREAD

**Issue by yurivict** [dwavesystems/dwave-samplers#60]
```
Compiling dwave/samplers/tree/sample.pyx because it changed.
Compiling dwave/samplers/tree/solve.pyx because it changed.
Compiling dwave/samplers/tree/utilities.pyx because it changed.
[1/3] Cythonizing dwave/samplers/tree/sample.pyx

Error compiling Cython file:
------------------------------------------------------------
...
                         double** single_mrg_data, int* single_mrg_len,
                         double** pair_mrg_data, int* pair_mrg_rows, int* pair_mrg_cols,
                         int** pair_data, int* pair_rows, int* pair_cols) except +

@cython.annotation_typing(False)  # maintain Cython2 behavior
def sample_bqm_wrapper(bqm: BinaryQuadraticModel,
^
------------------------------------------------------------

dwave/samplers/tree/sample.pyx:52:0: The annotation_typing compiler directive is not allowed in function scope
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 53, in <module>
    ext_modules=cythonize(
  File "/usr/local/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1115, in cythonize
    cythonize_one(*args)
  File "/usr/local/lib/python3.9/site-packages/Cython/Build/Dependencies.py", line 1238, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: dwave/samplers/tree/sample.pyx
*** Error code 1

```

Version: 1.2.0

FreeBSD 13.2

**Comment by yurivict** [comment]
Ok, thanks.
