### ISSUE TITLE
2 tests fail

### ISSUE THREAD

**Issue by yurivict** [dwavesystems/dwave-samplers#66]
```
======================================================================
FAIL: test_time_limit (test_random_sampler.TestRandomSampler.test_time_limit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports/science/py-dwave-samplers/work-py311/dwave-samplers-1.3.0/tests/test_random_sampler.py", line 62, in test_time_limit
    self.assertTrue(.01 < runtime < .04)
AssertionError: False is not true

======================================================================
FAIL: test_concurrency (test_tabu.TestTabuSearch.test_concurrency)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ports/science/py-dwave-samplers/work-py311/dwave-samplers-1.3.0/tests/test_tabu.py", line 69, in test_concurrency
    self.assertTrue(0.4 < tt.dt < 1.6)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 455 tests in 65.388s

FAILED (failures=2)
```

Version: 1.3.0
Python-3.11
FreeBSD 14.1

**Comment by arcondello** [comment]
Can you say more about the environment you're running this in? Is it single threaded?

**Comment by yurivict** [comment]
I run pytest, which is single threaded.

**Comment by arcondello** [comment]
For the
```
Traceback (most recent call last):
  File "/usr/ports/science/py-dwave-samplers/work-py311/dwave-samplers-1.3.0/tests/test_random_sampler.py", line 62, in test_time_limit
    self.assertTrue(.01 < runtime < .04)
AssertionError: False is not true
```
error, does it happen consistently or just sporadically?

**Comment by arcondello** [comment]
https://github.com/dwavesystems/dwave-samplers/pull/67 made some changes to the tests which should resolve this. Closing for now. If the issue persists please feel free to reopen the issue.
